# DigitalOcean App Platform deployment config
name: baby-raffle-api
services:
- name: api
  source_dir: /
  github:
    repo: your-username/baby-raffle-serverless
    branch: main
  run_command: uvicorn main:app --host 0.0.0.0 --port 8080
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  health_check:
    http_path: /health
  envs:
  - key: DB_HOST
    value: margojones-babyraffle-db.cu1y2a26idsb.us-east-1.rds.amazonaws.com
  - key: DB_PORT
    value: "5432"
  - key: DB_NAME
    value: babyraffle
  - key: DB_USERNAME
    value: postgres
  - key: DB_PASSWORD
    value: YgrzO9oHQScN5ctXcTOL
    type: SECRET
domains:
- domain: api.margojones.base2ml.com
  type: PRIMARY
