# Fly.io deployment config
app = "baby-raffle-api"
primary_region = "iad"

[build]

[env]
  DB_HOST = "margojones-babyraffle-db.cu1y2a26idsb.us-east-1.rds.amazonaws.com"
  DB_PORT = "5432"
  DB_NAME = "babyraffle"
  DB_USERNAME = "postgres"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  
[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
