version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=margojones-babyraffle-db.cu1y2a26idsb.us-east-1.rds.amazonaws.com
      - DB_PORT=5432
      - DB_NAME=babyraffle
      - DB_USERNAME=postgres
      - DB_PASSWORD=YgrzO9oHQScN5ctXcTOL
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
